In [2]:
%matplotlib inline
import cv2
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import os

## 1. Escala de grises

In [3]:
def graycolor(img):
    image = cv2.imread(img)
    cv_gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
    return cv_gray

### Mujeres

In [9]:
f_carpetas = os.listdir('faces/female')

In [42]:
os.mkdir("EG_F")

In [43]:
path = "EG_F/"
for carp in f_carpetas:
    sub = os.listdir('faces/female/'+carp)
    for img in sub:
        file = 'faces/female/'+carp+"/"+img
        try:
            gray = graycolor(file)
            cv2.imwrite(os.path.join(path , img), gray)
            cv2.waitKey(0)
        except:
            continue

In [45]:
len(os.listdir("EG_F"))

399

### Hombres

In [4]:
m_carpetas = os.listdir('faces/male')
len(m_carpetas)

113

In [51]:
aleatorio = []
while len(aleatorio) <20:
    num = np.random.randint(113)
    if num in aleatorio:
        continue
    else:
        aleatorio.append(num)

In [52]:
len(aleatorio)

20

In [53]:
os.mkdir("EG_M")

In [54]:
path = "EG_M/"
for i in aleatorio:
    carp = 'faces/male/'+ m_carpetas[i]
    sub = os.listdir(carp)
    for img in sub:
        file = carp+"/"+img
        try:
            gray = graycolor(file)
            cv2.imwrite(os.path.join(path , img), gray)
            cv2.waitKey(0)
            #print(file)
        except:
            continue

In [55]:
len(os.listdir("EG_M"))

400

## 2. Extraer Vectores Caracteristicos

**accediendo a carpeta de trabajo**

In [2]:
os.listdir("../databases")

['EG_F', 'EG_M', 'Hog', 'faces']

In [3]:
os.chdir("../databases"), os.listdir()

(None, ['EG_F', 'EG_M', 'Hog', 'faces'])

### 2.1 Concatenar

En un vector para M y F

In [7]:
def extraeVector(image):
    img = cv2.imread(image)
    cv_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    return list(cv_gray.ravel())

#### Mujeses

In [4]:
mujeres = os.listdir("EG_F")
len(mujeres)

399

In [9]:
female = []
for image in mujeres:
    vec = extraeVector('EG_F/'+image)
    female.append(vec)

In [10]:
female = np.array(female)
female.shape

(399, 36000)

#### Hoombres

In [5]:
hombres = os.listdir("EG_M")[:-1]
len(hombres)

399

In [12]:
male = []
for image in hombres:
    vec = extraeVector('EG_M/'+image)
    male.append(vec)

In [13]:
male = np.array(male)
male.shape

(399, 36000)

#### 2.1.1 PCA

In [14]:
from sklearn.decomposition import PCA

In [15]:
#MUJERES
pca = PCA(n_components=10)
PCAFemale = pca.fit_transform(female)

In [16]:
PCAFemale = pd.DataFrame(data=PCAFemale,
                   columns=["comp1","comp2","comp3","comp4","comp5",
                            "comp6","comp7","comp8","comp9","comp10"])
PCAFemale.head()

comp1        comp2        comp3       comp4        comp5  \
0  3332.658797 -1571.427508   569.498921 -875.028444  -442.384966   
1  3375.603024 -2467.036414  -381.361538    6.202025  2807.441617   
2 -6429.357040 -3630.252199 -1362.103595 -354.267715  2386.927032   
3  7957.378873 -1249.391673  -566.794251 -761.488113  1299.307416   
4  1624.824966 -1779.552152  -350.769143 -776.591574 -1361.591970   

         comp6        comp7        comp8        comp9       comp10  
0 -2619.423838  -344.317196 -1286.320936    60.252548  2003.012736  
1  -598.126956   221.097276 -1047.190558   140.946255  1367.767043  
2   128.379549   884.071526 -2152.868232  -509.951895   516.006082  
3 -1110.461565   528.848087   -68.020410  1822.671284   864.210518  
4 -1262.443450 -1309.651303  -772.186652  -345.804005   477.312084

In [17]:
#HOMBRES
pca = PCA(n_components=10)
PCAMale = pca.fit_transform(male)

In [18]:
PCAMale = pd.DataFrame(data=PCAMale,
                   columns=["comp1","comp2","comp3","comp4","comp5",
                            "comp6","comp7","comp8","comp9","comp10"])
PCAMale.head()

comp1        comp2        comp3        comp4        comp5  \
0  2925.290478   420.238903 -2350.792841  -361.905468  -501.864950   
1 -1093.303275 -4949.874867 -3578.779879  1498.319461 -1242.512777   
2 -2244.867709  3405.273167   941.848473  2645.450353  5472.047733   
3  -640.893722 -3573.628754  -593.127809 -3279.369843   220.802343   
4 -2968.293045  3667.168584  2038.051202 -3445.821411   895.148996   

         comp6        comp7        comp8        comp9       comp10  
0  1119.883543   620.995331  -237.479863  -620.765740   -55.996889  
1   487.686908  -833.933390   839.994620  -771.451292  1960.352211  
2 -1918.305834  2971.247879   985.382512 -1172.523848  1545.641532  
3  1385.721606   264.911401   669.443868 -2585.494080   427.768144  
4  4297.164550  2108.220282 -3245.916283   715.374229    60.445494

### 2.2 HOG

En un vector para M y F

In [6]:
def getHog(img):
    hog = cv2.HOGDescriptor()
    img = cv2.imread(img)
    cv_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    fv = hog.compute(cv_gray)
    return fv

**MUJERES**

In [7]:
fem_HOG = []
for image in mujeres:
    vec = getHog('EG_F/'+image)
    fem_HOG.append(vec)

In [8]:
fem_HOG = np.array(fem_HOG)[:,:,0]
fem_HOG.shape

(399, 567000)

In [10]:
fem_HOG[0:2,:]

array([[0.05096107, 0.10079551, 0.09052139, ..., 0.31633756, 0.31633756,
        0.05407228],
       [0.1692165 , 0.01800744, 0.04932511, ..., 0.19001985, 0.32638904,
        0.26495665]], dtype=float32)

**HOMBRES**

In [11]:
male_HOG = []
for image in hombres:
    vec = getHog('EG_M/'+image)
    male_HOG.append(vec)

In [12]:
male_HOG = np.array(male_HOG)[:,:,0]
male_HOG.shape

(399, 567000)

**Guardar vectores**

In [13]:
os.mkdir("FV_HOG")

In [15]:
print("tipo: ",type(fem_HOG), type(male_HOG))

tipo:  <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [18]:
np.save("FV_HOG/fem_HOG.npy", fem_HOG)
np.save("FV_HOG/male_HOG.npy", male_HOG)

### 2.3 SIFT

En carpetas

In [31]:
def getSift(img):
    sift = cv2.xfeatures2d.SIFT_create()
    img = cv2.imread(img)
    cv_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    kp, des = sift.detectAndCompute(cv_gray,None)
    return des

In [32]:
os.mkdir("FV_SIFT")
os.mkdir("FV_SIFT/female")
os.mkdir("FV_SIFT/male")

**MUJERES**

In [61]:
getSift("EG_F/"+mujeres[1]).shape

(96, 128)

In [53]:
".".join(mujeres[3].split(".")[:-1])

'sbains.15'

In [62]:
for image in mujeres:
    vec = getSift('EG_F/'+image)
    name = ".".join(image.split(".")[:-1])
    np.save("FV_SIFT/female/"+name+".npy", vec)#GUARDA

In [73]:
len(os.listdir("FV_SIFT/female"))

399

**HOMBRES**

In [63]:
for image in hombres:
    vec = getSift('EG_M/'+image)
    name = ".".join(image.split(".")[:-1])
    np.save("FV_SIFT/male/"+name+".npy", vec)#GUARDA

In [74]:
len(os.listdir("FV_SIFT/male"))

399

### 2.4 SURF

En carpetas

In [68]:
def getSurf(img):
    surf = cv2.xfeatures2d_SURF.create(400)
    img = cv2.imread(img)
    cv_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    kp, des = surf.detectAndCompute(cv_gray,None)
    return des

In [66]:
os.mkdir("FV_SURF")
os.mkdir("FV_SURF/female")
os.mkdir("FV_SURF/male")

**MUJERES**

In [69]:
for image in mujeres:
    vec = getSurf('EG_F/'+image)
    name = ".".join(image.split(".")[:-1])
    np.save("FV_SURF/female/"+name+".npy", vec)#GUARDA

In [71]:
len(os.listdir("FV_SURF/female"))

399

**HOMBRES**

In [70]:
for image in hombres:
    vec = getSurf('EG_M/'+image)
    name = ".".join(image.split(".")[:-1])
    np.save("FV_SURF/male/"+name+".npy", vec)#GUARDA

In [72]:
len(os.listdir("FV_SURF/male"))

399

## 3. Features Vectors Intermediate

In [3]:
os.listdir("../databases")

['FV_SIFT', 'FV_HOG', 'EG_F', 'EG_M', 'FV_SURF', 'Hog', 'faces']

In [4]:
os.chdir("../databases")

### 3.1 k - means  - Bag of Visual Words(BoVW)

In [1]:
from sklearn.cluster import KMeans

### 3.1.1  SIFT

In [9]:
path = "FV_SIFT"
os.listdir(path)

['male', 'female']

**MUJERES**

In [10]:
sift_female = os.listdir(path+"/female")
len(sift_female)

399

In [26]:
array_female = []
for vector in sift_female:
    array_female.append(np.load(path+"/female/"+vector))
len(array_female)

399

In [27]:
array_female = np.concatenate(array_female,axis = 0)
array_female.shape

(47896, 128)

**HOMBRES**

In [28]:
sift_male = os.listdir(path+"/male")
len(sift_male)

399

In [29]:
array_male = []
for vector in sift_male:
    array_male.append(np.load(path+"/male/"+vector))
len(array_male)

399

In [30]:
array_male = np.concatenate(array_male,axis = 0)
array_male.shape

(64310, 128)

**UNION**

In [31]:
array_final = np.concatenate([array_female,array_male],axis = 0)
array_final.shape

(112206, 128)

**KMEANS**

In [32]:
kmeans = KMeans(n_clusters=10).fit(array_final)

In [34]:
kmeans.labels_.shape,kmeans.cluster_centers_.shape

((112206,), (10, 128))

In [35]:
prueba1 = np.load(path+"/female/"+sift_female[1])
prueba1.shape

(61, 128)

In [36]:
prueba1[:1,:]

array([[ 31.,  32.,  18.,   1.,   2.,   2.,   0.,   2., 137., 137.,   6.,
          0.,   0.,   0.,   0.,  16.,  62., 125.,  76.,  98.,  43.,   0.,
          0.,   5.,  19.,   0.,   5.,  88., 103.,   2.,   2.,  40.,  65.,
          2.,   0.,   0.,   2.,  12.,   7.,   9., 137.,  15.,   1.,   0.,
          2.,   2.,   4.,  85.,  37.,  20.,  20.,  38.,  72.,  19.,   8.,
         34., 137.,   1.,   3.,  38.,  41.,   2.,   1., 115.,  37.,   1.,
          0.,   0.,   2.,  10.,   5.,   7., 137.,  29.,   1.,   1.,   4.,
          1.,   1.,  13.,  45.,  13.,   1.,  12., 120.,  11.,   2.,   5.,
        137.,   5.,   0.,   5.,  37.,   5.,   2., 102.,   2.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,  22.,   1.,   0.,   0.,   0.,   0.,
          0.,   1.,   8.,   2.,   0.,   6.,  21.,   0.,   0.,   0., 137.,
          4.,   1.,   4.,   7.,   0.,   0.,  13.]], dtype=float32)

In [42]:
kmeans.predict(prueba1[:1,:])[0]

8

In [209]:
def vectorKmeans(array,kmeans):
    row, col = array.shape
    vector = np.zeros(100)#para SURF 100
    for i in range(row):
        k = kmeans.predict(array[i:i+1,:])[0]
        vector[k]=vector[k]+1
    return vector

In [52]:
prueba2 = np.load(path+"/female/"+sift_female[2])
prueba2.shape

(144, 128)

In [82]:
vectorKmeans(prueba2,kmeans)

array([10., 30., 18., 16.,  4., 14., 21., 11., 13.,  7.])

**Vectores Kmeans - Mujeres**

In [67]:
female_sift_kmeans = []
for vector in sift_female:
    vec = np.load(path+"/female/"+vector)
    female_sift_kmeans.append(vectorKmeans(vec,kmeans))
len(female_sift_kmeans)

399

In [70]:
female_sift_kmeans = np.array(female_sift_kmeans)
female_sift_kmeans.shape

(399, 10)

**Vectores Kmeans - Hombres**

In [69]:
male_sift_kmeans = []
for vector in sift_male:
    vec = np.load(path+"/male/"+vector)
    male_sift_kmeans.append(vectorKmeans(vec))
len(male_sift_kmeans)

399

In [71]:
male_sift_kmeans = np.array(male_sift_kmeans)
male_sift_kmeans.shape

(399, 10)

### 3.1.2 SURF

In [72]:
path = "FV_SURF"
os.listdir(path)

['male', 'female']

**Mujeres**

In [73]:
surf_female = os.listdir(path+"/female")
len(surf_female)

399

In [90]:
surf_array_female = []
for vector in surf_female:
    surf_array_female.append(np.load(path+"/female/"+vector))
len(surf_array_female)

399

In [91]:
surf_array_female = np.concatenate(surf_array_female,axis = 0)
surf_array_female.shape

(34361, 64)

**Hombres**

In [92]:
surf_male = os.listdir(path+"/male")
len(surf_male)

399

In [93]:
surf_array_male = []
for vector in surf_male:
    surf_array_male.append(np.load(path+"/male/"+vector))
len(surf_array_male)

399

In [94]:
surf_array_male = np.concatenate(surf_array_male,axis = 0)
surf_array_male.shape

(45270, 64)

**UNION ARRAYS**

In [95]:
array_final_surf = np.concatenate([surf_array_female,surf_array_male],axis = 0)
array_final_surf.shape

(79631, 64)

**KMEANS**

In [207]:
kmeans_SURF = KMeans(n_clusters=100).fit(array_final_surf)
kmeans_SURF.labels_.shape,kmeans_SURF.cluster_centers_.shape

((79631,), (100, 64))

**Kmeans -Mujeres**

In [210]:
female_surf_kmeans = []
for vector in surf_female:
    vec = np.load(path+"/female/"+vector)
    female_surf_kmeans.append(vectorKmeans(vec,kmeans_SURF))
len(female_surf_kmeans)

399

In [211]:
female_surf_kmeans = np.array(female_surf_kmeans)
female_surf_kmeans.shape

(399, 100)

**Kmeans - Hombres**

In [212]:
male_surf_kmeans = []
for vector in surf_male:
    vec = np.load(path+"/male/"+vector)
    male_surf_kmeans.append(vectorKmeans(vec,kmeans_SURF))
len(male_surf_kmeans)

399

In [213]:
male_surf_kmeans = np.array(male_surf_kmeans)
male_surf_kmeans.shape

(399, 100)

## 4 Moldelado

### 4.1 SVM

In [101]:
import pandas as pd

**Data Mujeres con SURF**

In [214]:
df_mujeres = pd.DataFrame()
df_mujeres["nombre"] = surf_female
df_mujeres["data"] = list(female_surf_kmeans)
df_mujeres["target"] = 0
df_mujeres.head(3)

nombre                                               data  target
0   sbains.19.npy  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ...       0
1    mbutle.2.npy  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 2.0, ...       0
2  9338535.10.npy  [1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 4.0, ...       0

In [108]:
#df_female_surf_kmeans = pd.DataFrame(data=female_surf_kmeans,
#                   columns=["centroid1","centroid2","centroid3","centroid4","centroid5",
#                            "centroid6","centroid7","centroid8","centroid9","centroid10"])
#df_female_surf_kmeans.head()

**Data Hombres con SURF**

In [215]:
df_hombres = pd.DataFrame()
df_hombres["nombre"] = surf_male
df_hombres["data"] = list(male_surf_kmeans)
df_hombres["target"] = 1
df_hombres.head(3)

nombre                                               data  target
0   dakram.7.npy  [2.0, 1.0, 3.0, 1.0, 6.0, 1.0, 0.0, 4.0, 0.0, ...       1
1  rarobi.13.npy  [0.0, 0.0, 1.0, 3.0, 2.0, 2.0, 0.0, 0.0, 0.0, ...       1
2  mefait.16.npy  [0.0, 2.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, ...       1

In [216]:
data_gender = pd.concat([df_mujeres,df_hombres])
data_gender.head()

nombre                                               data  target
0   sbains.19.npy  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ...       0
1    mbutle.2.npy  [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 2.0, ...       0
2  9338535.10.npy  [1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 4.0, ...       0
3  9336923.14.npy  [0.0, 4.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 2.0, ...       0
4    kaknig.4.npy  [1.0, 2.0, 0.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, ...       0

In [217]:
data_gender.groupby("target").size()

target
0    399
1    399
dtype: int64

**Train Test**

In [114]:
from sklearn import svm
from sklearn.model_selection import train_test_split

In [218]:
X = np.stack(data_gender.data,axis=0)
Y = data_gender.target

In [167]:
#type(X.as_matrix())

In [219]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.20,random_state=42)

In [220]:
X_train.shape,Y_train.shape

((638, 100), (638,))

In [221]:
X_test.shape,Y_test.shape

((160, 100), (160,))

In [171]:
#np.array(X_train)

**Modelado**

In [172]:
clasificador = svm.SVC()

In [222]:
clasificador.fit(X_train,Y_train)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [223]:
Y_pred = clasificador.predict(X_test)

In [224]:
Y_test[23:24]

320    1
Name: target, dtype: int64

In [225]:
#data_gender.loc[:,2]

In [226]:
Y_pred[23]

0

In [227]:
from sklearn.metrics import accuracy_score

accuracy_score(Y_test, Y_pred)

0.9875

In [193]:
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(Y_test,Y_pred)

array([[68, 12],
       [18, 62]])

In [187]:
clasificador = svm.SVC(gamma=0.0001,C=100)